require:
  - rubocop-rake
  - rubocop-minitest


AllCops:
  NewCops: enable
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
